[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_endpoints = { hoodi = "https://eth-hoodi.g.alchemy.com/v2/tqG_1kOtuO5_Isg5E__dU", sepolia = "https://eth-sepolia.g.alchemy.com/v2/W0_zQVvK7NajymL6rQBsN" }

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",

    "@chainlink/contracts-ccip/=lib/chainlink-ccip/chains/evm/",
    "@chainlink/contracts/=lib/chainlink-local/lib/chainlink-evm/contracts/",

    "@chainlink/local/=lib/chainlink-local/",

    "@openzeppelin/contracts@4.7.3/=lib/chainlink-local/src/vendor/openzeppelin-solidity/v4.7.3/contracts/",
    "@openzeppelin/contracts@4.8.3/=lib/chainlink-local/src/vendor/openzeppelin-solidity/v4.8.3/contracts/",
    "@openzeppelin/contracts@5.0.2/=lib/chainlink-local/src/vendor/openzeppelin-solidity/v5.0.2/contracts/",
]
